# Simple Queue Service on Amazon test!
#
# This is a concept service for the enqueue system!

service: sqs-test
frameworkVersion: '2'
provider:
  apiGateway:
   shouldStartNameWithService: true
  name: aws
  environment:
    AWS_SQS_QUEUE_URL:
      Ref: SampleQueue
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage,'dev'}
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        Fn::GetAtt:
          - SampleQueue
          - Arn

plugins:
  - serverless-plugin-optimize

package:
  individually: true
  include:
    - src/**
  exclude:
    - node_modules/aws-sdk/**

functions:
  enqueue:
    handler: src/lambdas/handler/handler.enqueueAction
    description: Hanlder function
    memorySize: 512
    events:
      - http:
          path: enqueue
          method: POST
          cors: true
          headers:
            - Content-Type


  queue:
    handler: src/lambdas/queue/queue.handleQueueAction
    description: This function handle the created queue
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SampleQueue
              - Arn
          batchSize: 1
          enabled: true

resources:
  Description: Sample stack for test SQS
  Resources:
    SampleQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SampleQueue
